import { PrismaClient, Products } from '@prisma/client'
const prisma = new PrismaClient();

const products: Products[] = [
  {
    id: 11,
    name: 'Aerofolio',
    description: 'Acessorio de carro esportivo',
    price: 180,
    sold: false,
    categoriesId: 1,
    new: false,
    usersId: '11',
  },
  {
    id: 12,
    name: 'Vinho Tinto',
    description: 'Vinho tinto frances',
    price: 800,
    sold: false,
    new: true,
    categoriesId: 2,
    usersId: '20',
  },
  {
    id: 13,
    name: 'Coleira',
    description: 'Coleira para cachorro grande',
    price: 80,
    sold: false,
    new: true,
    categoriesId: 3,
    usersId: '12',
  },
  {
    id: 14,
    name: 'Vaso Chines',
    description: 'Vaso importado da chines',
    price: 7000,
    sold: false,
    new: false,
    categoriesId: 4,
    usersId: '19',
  },
  {
    id: 15,
    name: 'Tela para pintura',
    description: 'Tela branca em tecido',
    price: 50,
    sold: false,
    new: true,
    categoriesId: 5,
    usersId: '13',
  },
  {
    id: 16,
    name: 'Mamadeira',
    description: 'Mamadeira cor rosa',
    price: 30,
    sold: false,
    new: true,
    categoriesId: 6,
    usersId: '18',
  },
  {
    id: 17,
    name: 'Baton Rose',
    description: 'Batom rosa mate',
    price: 100,
    sold: false,
    new: true,
    categoriesId: 7,
    usersId: '14',
  },
  {
    id: 18,
    name: 'Bola de futebol',
    description: 'Bola de futebol FiFa original',
    price: 200,
    sold: false,
    new: false,
    categoriesId: 8,
    usersId: '17',
  },
  {
    id: 19,
    name: 'Bolsa Guci',
    description: 'Bolsa importada Guci',
    price: 5000,
    sold: false,
    new: false,
    categoriesId: 9,
    usersId: '15',
  },
  {
    id: 20,
    name: 'Mesa de centro',
    description: 'Mesinha de centro com tampa de vidro',
    price: 500,
    sold: false,
    new: false,
    categoriesId: 10,
    usersId: '16',
  },
  {
    id: 21,
    name: 'Celular Sammung 7',
    description: 'Celular com 5 cameras 10 gigas memoria e 100gb de armazenamento',
    price: 4100,
    sold: false,
    new: true,
    categoriesId: 11,
    usersId: '16',
  },
  {
    id: 22,
    name: 'Geladeira duas portas',
    description: 'Geladeiras de duas portas super congelante',
    price: 3800,
    sold: false,
    new: false,
    categoriesId: 12,
    usersId: '15',
  },
  {
    id: 23,
    name: 'Tv FullHd 29',
    description: 'Smarth Tv FullHd de 29 polegadas',
    price: 6000,
    sold: false,
    new: true,
    categoriesId: 13,
    usersId: '17',
  },
  {
    id: 24,
    name: 'Cesta de basquete',
    description: 'Cesta de basquete profissional',
    price: 900,
    sold: false,
    new: false,
    categoriesId: 14,
    usersId: '14',
  },
  {
    id: 25,
    name: 'Martelo',
    description: 'Martelo de ferro fundido Dragao',
    price: 600,
    sold: false,
    new: true,
    categoriesId: 15,
    usersId: '18',
  },
  {
    id: 26,
    name: 'Chapeu de festa infantil',
    description: 'Capeu de festa cores sortidos',
    price: 30,
    sold: false,
    new: true,
    categoriesId: 16,
    usersId: '13',
  },
  {
    id: 27,
    name: 'Xbox Two',
    description: 'Console Xbox two com 10 games',
    price: 1400,
    sold: false,
    new: false,
    categoriesId: 17,
    usersId: '19',
  },
  {
    id: 28,
    name: 'Britadeira',
    description: 'Britadeira aw150 industrial',
    price: 7000,
    sold: false,
    new: false,
    categoriesId: 18,
    usersId: '12',
  },
  {
    id: 29,
    name: 'Macbook Pro 18',
    description: 'Computar apple macbook pro 18',
    price: 18000,
    sold: false,
    new: true,
    categoriesId: 19,
    usersId: '20',
  },
  {
    id: 30,
    name: 'Guitarra Eletrica Gibsom',
    description: 'Guitarra eletrica anos 90 Gibsom',
    price: 20000,
    sold: false,
    new: false,
    categoriesId: 20,
    usersId: '11',
  },
  {
    id: 31,
    name: 'Colecao Cronicas do vento',
    description: 'Colecao 7 livros cronicas do vento de R.R. Tolmen',
    price: 360,
    sold: false,
    new: false,
    categoriesId: 21,
    usersId: '19',
  },
  {
    id: 32,
    name: 'Aparelho de DVD',
    description: 'Aparelho de dvd usado + 50 dvds',
    price: 400,
    sold: false,
    new: false,
    categoriesId: 22,
    usersId: '11',
  },
  {
    id: 33,
    name: 'Termometro',
    description: 'Termometro digital ',
    price: 110,
    sold: false,
    new: true,
    categoriesId: 23,
    usersId: '18',
  },
  {
    id: 34,
    name: 'Maquina de cortar grama ',
    description: 'Maquina de cortar grama zx190',
    price: 450,
    sold: false,
    new: false,
    categoriesId: 24,
    usersId: '11',
  },
  {
    id: 35,
    name: 'Suporte de GPS',
    description: 'Suporte para celular e GPS',
    price: 50,
    sold: false,
    categoriesId: 1,
    new: true,
    usersId: '20',
  },
  {
    id: 36,
    name: 'Balas Finas',
    description: 'Balas de goma finas sabor sortido',
    price: 15,
    sold: false,
    new: true,
    categoriesId: 2,
    usersId: '19',
  },
  {
    id: 37,
    name: 'Alimentador de plastico',
    description: 'Alimentador para caes e gatos de plastico',
    price: 110,
    sold: false,
    new: true,
    categoriesId: 3,
    usersId: '18',
  },
  {
    id: 38,
    name: 'Tapete',
    description: 'Tapete italiano de 1900',
    price: 5500,
    sold: false,
    new: false,
    categoriesId: 4,
    usersId: '17',
  },
  {
    id: 39,
    name: 'Caderno 20 materias',
    description: 'Caderno 20 materias 200 folhas',
    price: 45,
    sold: false,
    new: true,
    categoriesId: 5,
    usersId: '16',
  },
  {
    id: 40,
    name: 'Berco',
    description: 'Berco para criancas de 0 a 2 anos',
    price: 300,
    sold: false,
    new: false,
    categoriesId: 6,
    usersId: '15',
  },
  {
    id: 41,
    name: 'Shampo Ceda',
    description: 'Shampo 2 em 1 Ceda',
    price: 70,
    sold: false,
    new: true,
    categoriesId: 7,
    usersId: '14',
  },
  {
    id: 42,
    name: 'Raquete de Tenis',
    description: 'Raquete de Tenis Usada',
    price: 250,
    sold: false,
    new: false,
    categoriesId: 8,
    usersId: '13',
  },
  {
    id: 43,
    name: 'Calca jeans Levis',
    description: 'calca jeans levis tamanho 43',
    price: 300,
    sold: false,
    new: false,
    categoriesId: 9,
    usersId: '12',
  },
  {
    id: 44,
    name: 'Sofa',
    description: 'Sofa de 6 lugares vermelho',
    price: 750,
    sold: false,
    new: false,
    categoriesId: 10,
    usersId: '11',
  },
  {
    id: 45,
    name: 'Xioni A75',
    description: 'Celular com 5 cameras 10 gigas memoria e 100gb de armazenamento',
    price: 4100,
    sold: false,
    new: true,
    categoriesId: 11,
    usersId: '19',
  },
  {
    id: 46,
    name: 'Capa de Carro',
    description: 'Acessorio de carro esportivo',
    price: 180,
    sold: false,
    categoriesId: 1,
    new: false,
    usersId: '11',
  },
  {
    id: 47,
    name: 'Macarrao instantaneo',
    description: 'Macarrao instantaneo',
    price: 5,
    sold: false,
    new: true,
    categoriesId: 2,
    usersId: '12',
  },
  {
    id: 48,
    name: 'Cama',
    description: 'Cama para cachorro grande',
    price: 50,
    sold: false,
    new: true,
    categoriesId: 3,
    usersId: '12',
  },
  {
    id: 49,
    name: 'Vaso Chines',
    description: 'Vaso importado da chines',
    price: 7000,
    sold: false,
    new: false,
    categoriesId: 4,
    usersId: '19',
  },
  {
    id: 50,
    name: 'Lapis',
    description: 'Tela branca em tecido',
    price: 50,
    sold: false,
    new: true,
    categoriesId: 5,
    usersId: '13',
  },
  {
    id: 51,
    name: 'Mamadeira',
    description: 'Mamadeira cor rosa',
    price: 30,
    sold: false,
    new: true,
    categoriesId: 6,
    usersId: '18',
  },
  {
    id: 52,
    name: 'Baton Rose',
    description: 'Batom rosa mate',
    price: 100,
    sold: false,
    new: true,
    categoriesId: 7,
    usersId: '14',
  },
  {
    id: 53,
    name: 'Bola de futebol',
    description: 'Bola de futebol FiFa original',
    price: 200,
    sold: false,
    new: false,
    categoriesId: 8,
    usersId: '17',
  },
  {
    id: 54,
    name: 'Bolsa Guci',
    description: 'Bolsa importada Guci',
    price: 5000,
    sold: false,
    new: false,
    categoriesId: 9,
    usersId: '15',
  },
  {
    id: 55,
    name: 'Mesa de centro',
    description: 'Mesinha de centro com tampa de vidro',
    price: 500,
    sold: false,
    new: false,
    categoriesId: 10,
    usersId: '16',
  },
  {
    id: 56,
    name: 'Celular Sammung 7',
    description: 'Celular com 5 cameras 10 gigas memoria e 100gb de armazenamento',
    price: 4100,
    sold: false,
    new: true,
    categoriesId: 11,
    usersId: '16',
  },
  {
    id: 57,
    name: 'Geladeira duas portas',
    description: 'Geladeiras de duas portas super congelante',
    price: 3800,
    sold: false,
    new: false,
    categoriesId: 12,
    usersId: '15',
  },
  {
    id: 58,
    name: 'Tv FullHd 29',
    description: 'Smarth Tv FullHd de 29 polegadas',
    price: 6000,
    sold: false,
    new: true,
    categoriesId: 13,
    usersId: '17',
  },
  {
    id: 59,
    name: 'Cesta de basquete',
    description: 'Cesta de basquete profissional',
    price: 900,
    sold: false,
    new: false,
    categoriesId: 14,
    usersId: '14',
  },
  {
    id: 60,
    name: 'Martelo',
    description: 'Martelo de ferro fundido Dragao',
    price: 600,
    sold: false,
    new: true,
    categoriesId: 15,
    usersId: '18',
  },
  {
    id: 61,
    name: 'Chapeu de festa infantil',
    description: 'Capeu de festa cores sortidos',
    price: 30,
    sold: false,
    new: true,
    categoriesId: 16,
    usersId: '13',
  },
  {
    id: 62,
    name: 'Xbox Two',
    description: 'Console Xbox two com 10 games',
    price: 1400,
    sold: false,
    new: false,
    categoriesId: 17,
    usersId: '19',
  },
  {
    id: 63,
    name: 'Britadeira',
    description: 'Britadeira aw150 industrial',
    price: 7000,
    sold: false,
    new: false,
    categoriesId: 18,
    usersId: '12',
  },
  {
    id: 64,
    name: 'Macbook Pro 18',
    description: 'Computar apple macbook pro 18',
    price: 18000,
    sold: false,
    new: true,
    categoriesId: 19,
    usersId: '20',
  },
  {
    id: 65,
    name: 'Guitarra Eletrica Gibsom',
    description: 'Guitarra eletrica anos 90 Gibsom',
    price: 20000,
    sold: false,
    new: false,
    categoriesId: 20,
    usersId: '11',
  },
  {
    id: 66,
    name: 'Colecao Cronicas do vento',
    description: 'Colecao 7 livros cronicas do vento de R.R. Tolmen',
    price: 360,
    sold: false,
    new: false,
    categoriesId: 21,
    usersId: '19',
  },
  {
    id: 67,
    name: 'Aparelho de DVD',
    description: 'Aparelho de dvd usado + 50 dvds',
    price: 400,
    sold: false,
    new: false,
    categoriesId: 22,
    usersId: '11',
  },
  {
    id: 68,
    name: 'Termometro',
    description: 'Termometro digital ',
    price: 110,
    sold: false,
    new: true,
    categoriesId: 23,
    usersId: '18',
  },
  {
    id: 69,
    name: 'Maquina de cortar grama ',
    description: 'Maquina de cortar grama zx190',
    price: 450,
    sold: false,
    new: false,
    categoriesId: 24,
    usersId: '11',
  },
  {
    id: 70,
    name: 'Suporte de GPS',
    description: 'Suporte para celular e GPS',
    price: 50,
    sold: false,
    categoriesId: 1,
    new: true,
    usersId: '20',
  },
  {
    id: 71,
    name: 'Balas Finas',
    description: 'Balas de goma finas sabor sortido',
    price: 15,
    sold: false,
    new: true,
    categoriesId: 2,
    usersId: '19',
  },
  {
    id: 72,
    name: 'Alimentador de plastico',
    description: 'Alimentador para caes e gatos de plastico',
    price: 110,
    sold: false,
    new: true,
    categoriesId: 3,
    usersId: '18',
  },
  {
    id: 73,
    name: 'Tapete',
    description: 'Tapete italiano de 1900',
    price: 5500,
    sold: false,
    new: false,
    categoriesId: 4,
    usersId: '17',
  },
  {
    id: 74,
    name: 'Caderno 20 materias',
    description: 'Caderno 20 materias 200 folhas',
    price: 45,
    sold: false,
    new: true,
    categoriesId: 5,
    usersId: '16',
  },
  {
    id: 75,
    name: 'Berco',
    description: 'Berco para criancas de 0 a 2 anos',
    price: 300,
    sold: false,
    new: false,
    categoriesId: 6,
    usersId: '15',
  },
  {
    id: 76,
    name: 'Shampo Ceda',
    description: 'Shampo 2 em 1 Ceda',
    price: 70,
    sold: false,
    new: true,
    categoriesId: 7,
    usersId: '14',
  },
  {
    id: 77,
    name: 'Raquete de Tenis',
    description: 'Raquete de Tenis Usada',
    price: 250,
    sold: false,
    new: false,
    categoriesId: 8,
    usersId: '13',
  },
  {
    id: 78,
    name: 'Calca jeans Levis',
    description: 'calca jeans levis tamanho 43',
    price: 300,
    sold: false,
    new: false,
    categoriesId: 9,
    usersId: '12',
  },
  {
    id: 79,
    name: 'Sofa',
    description: 'Sofa de 6 lugares vermelho',
    price: 750,
    sold: false,
    new: false,
    categoriesId: 10,
    usersId: '11',
  },
  {
    id: 80,
    name: 'Xioni A75',
    description: 'Celular com 5 cameras 10 gigas memoria e 100gb de armazenamento',
    price: 4100,
    sold: false,
    new: true,
    categoriesId: 11,
    usersId: '19',
  }
];

async function productsSeed() {
  const resultProducts = products.map(async (products) =>{
    const response = await prisma.products.upsert({
      where: { id: products.id },
      update: {},
      create: {
        ...products,
      },
    })
    return response
  });

  await Promise.all(resultProducts);
};

productsSeed()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  });
